version: "3.9"
services:
  app:
    build: .
    image: ${IMAGE_NAME:-myapp}:latest
    ports: ["8080:8080"]
    environment:
      - APP_ENV=dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
